### PR TITLE
Update README's Usage steps

### PR DESCRIPTION
**Pull request by brettcannon**
List out the steps to use `venv`, activate the venv, and to not assume pip.

### CODE REVIEW

**Review by freakboy3742 — APPROVED** [review]
🎆

**Comment by brettcannon** [comment]
Before you merge, I just noticed that you create the `liquid` directory but never `cd` into it. Was that an oversight? And if so, want me to update this PR?

**Comment by freakboy3742** [comment]
Ooh - just in the nick of time. Yes - there should be a `cd` as well.

**Comment by brettcannon** [comment]
Done!

**Pull request merged**
